version: '3.6'

services:
  application:
    build: './development'
    command: sh -c "/wait && npm install && npm run start:local"
    restart: always
    working_dir: $PWD
    privileged: true
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    env_file: .env
    volumes:
      - $PWD:$PWD
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'local_db'
